#!/bin/bash

desktopid=$(xdotool get_desktop)
lineseparated_ids=$(wmctrl -l | cut -d' ' -f1,3 | grep $desktopid'$' | grep -o '0x[0-9a-f]*')
echo "lineseparated_id=$lineseparated_ids"

spaceseparated_ids=$(echo $lineseparated_ids | cut -d$'\n' -f1)
echo "spaceseparated_ids=$spaceseparated_ids"

IFS=' ' read -r -a ids <<< "$spaceseparated_ids"
echo "ids=$ids"

#active_win=$( wmctrl -lp | grep $(xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/') )
#active_id=$(echo $active_win | cut -d' ' -f1)

active_id=$(printf 0x%x $(xdotool getactivewindow)) # convert from dec to hex
echo "active_id=$active_id"

reverse=false
if [[ $1 = "reverse" ]]; then reverse=true; fi
echo "reverse=$reverse"

length=${#ids[@]}
echo "length=$length"

for ((i=0; i<length; i++))
do
	echo xxx
	echo "active_id=$active_id, id[i]=${ids[$i]}"
	
	if [[ $active_id -eq ${ids[$i]} ]]; then
		echo yyy
	
		next_idx=-1
		
		if [[ $reverse = "true" ]]; then
			echo "aaa"
			
			if [[ $((i-1)) -lt 0 ]]; then
				echo aaa1
				next_idx=$((length-1))
			else
				echo aaa2
				next_idx=$((i-1))
			fi
		else
			echo bbb
			if [[ $((i+1)) -eq $length ]]; then
				echo bbb1
				next_idx=0
			else
				echo bbb2
				next_idx=$((i+1))
			fi
		fi
		
		next_id=${ids[$next_idx]}
		dec_nextid=$(printf %i $next_id)
		
		echo "> Activate next window $next_id (dec=$dec_nextid) [i=$i, next_idx=$next_idx]"
		
		xdotool windowactivate $dec_nextid
		
		break
	fi
done

